version: '3.8'

services:
  bsc-fullnode:
    container_name: bsc-fullnode
    image: ghcr.io/bnb-chain/bsc:latest
    ports:
      - "8545:8545"         # JSON-RPC HTTP
      - "8546:8546"         # WebSocket
      - "30311:30311"       # P2P TCP
      - "30311:30311/udp"   # P2P UDP
      - "127.0.0.1:6060:6060"
    volumes:
      - ./config:/bsc/config:ro
      - ./data/node:/bsc/node
    stop_signal: SIGINT
    stop_grace_period: 2m
    restart: unless-stopped
    command: >
      --datadir /bsc/node
      --config /bsc/config/config.toml
      --syncmode snap
      --cache 8000
      --snapshot=true
      --pruneancient
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.vhosts '*'
      --http.api eth,net,web3,debug
      --http.corsdomain '*'
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --ws.api eth,net,web3,debug
      --ws.origins '*'
      --port 30311
      --metrics
      --pprof
      --pprof.addr 0.0.0.0
      --pprof.port 6060
      --verbosity 3
    networks:
      - bsc-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - "127.0.0.1:9090:9090"
    restart: unless-stopped
    depends_on:
      - bsc-fullnode
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://localhost:9090/-/healthy" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - bsc-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_LOG_LEVEL=warn
    restart: unless-stopped
    depends_on:
      - prometheus
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - bsc-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

volumes:
  bsc-data:
    name: bsc-data
  prometheus-data:
    name: prometheus-data
  grafana-data:
    name: grafana-data

networks:
  bsc-network:
    driver: bridge
    name: bsc-network