global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bsc-node'
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ['bsc-fullnode:6060']
        labels:
          instance: bsc-fullnode

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus